---
name: Unit Tests

# Trigger mega-linter at every push.
on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  run_tests:
    runs-on: self-hosted
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo $PATH

      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "21"
          cache: maven

      # Cach the maven packages
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

        # Build
      - name: Build
        run: /bin/mvn --batch-mode -DskipTests package

      # Test
      - name: Test
        run: /bin/mvn --batch-mode -Dmaven.test.failure.ignore=true test

      # Report test results
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests Results
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      # Report code coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ogi02/Questionnaire-Java-Backend
